name: Build and Release client

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: build-release

    steps:
    - uses: actions/checkout@v3

    - name: Copy config file
      run: cp config-prod.cfg config.cfg

    - name: Godot Export
      uses: firebelley/godot-export@v4.1.1
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: false

    - name: Package build output 
      run: >
        mkdir az-upload-dir;
        mkdir az-upload-dir/staging;
        cp -r /home/azureuser/.local/share/godot/builds/Windows\ Desktop/* az-upload-dir/staging;
        cd az-upload-dir/staging/;
        zip -r ../runners-gate-windows.zip .;
        cd ../..
      
    - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      name: Uploading to Azure storage...
      with:
        connection_string: ${{ secrets.AZ_STORAGE_ACCOUNT_CONNECTION_STRING }}
        container_name: release
        source_folder: az-upload-dir
